"use client"

import React, { useState } from "react"
import Image from "next/image"
import Link from "next/link"
import Logo from '../../public/Images/Logo.png'
import './layout.css'
import Home from "./page"
import Login from "./Login/page"
import { Route } from "@mui/icons-material"

export const metadata = {

  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
  const [token, setToken] = useState (localStorage.getItem("auth_token"))

  console.log(token);
 return (
    <html lang="en">
      <body>
        <div className="container">
          <div className="logo_div">
            <Image className="logo" src={Logo}/>
            <p className="logo_p">Продай, найди, купи все что пожелаешь…</p>
          </div>
          <div className="nav_menu">
            <Link className="site_nav-menu" href='/'>Home</Link>
            <Link className="site_nav-menu" href='/Profil'>Profil</Link>
            <Link className="site_nav-menu" href='/Shop'>Shop</Link>
            <Link className="site_nav-menu" href='/'>Home</Link>
          </div>
          <div className="nav_register">
            <Link className="site_register" href='/Login'>Login</Link>   
          </div>
          <div className="categories">
            
            {/* <Routes/> */}
          </div>
        </div>
        {children}        
      </body>
    </html>
  )
}
